twig:
    file_name_pattern: '*.twig'
    paths:
        'src/URLShooter/UI/Resources/views': ~
        'src/PostGenerator/UI/Resources/views': ~
        'src/AppGenerator/UI/Resources/views': ~

when@test:
    twig:
        strict_variables: true
