vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
    mappings:
        app_files:
            uri_prefix: /app-generator/files
            upload_destination: "%kernel.project_dir%/public/app-generator/files"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
