services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ":8088"
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins "http://127.0.0.1:8000"
        anonymous

    # Uncomment the following line to enable the development mode
    # command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - '8088:8088'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
  

volumes:
  mercure_data:
  mercure_config: