services:
  url-shooter-worker:
    image: laminecoder/url-shooter-worker:latest
    volumes:
      - worker_data:/home/minato
    ports:
      - ${URL_SHOOTER_WORKER_PORT}:3000
    networks:
      - internal-network
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - database
      - redis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - internal-network
  redis:
    restart: unless-stopped
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - internal-network

volumes:
  database_data:
  worker_data:

networks:
  internal-network:
