controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

url_shooter:
    resource: ../src/URLShooter/UI/Controller/
    type: attribute
post_generator:
    resource: ../src/PostGenerator/UI/Controller/
    type: attribute
app_generator:
    resource: ../src/AppGenerator/UI/Controller/
    type: attribute